/* Caribbean Guard safety map, service worker.
   ============================================================================

   WHY THIS EXISTS
   The map's whole reason to be is working at the water's edge, where there is no
   signal. Across eight verified national public safety map viewers in Latin
   America, not one registers a service worker or ships a manifest. Offline is not
   a standard this project is behind on; it is the gap the whole regional field
   leaves open, on a continent where the people most likely to need a hazard map
   are the ones least likely to have a bar of signal.

   THE PRECACHE LIST IS NOT HAND MAINTAINED AS AN addAll
   MDN, on install: "If the promise is rejected, the installation fails, and the
   worker won't do anything." cache.addAll() is all or nothing and the
   specification makes it reject on any response outside the ok range. So ONE 404
   in a hand-written list silently disables offline support entirely, with nothing
   visible to the user and nothing visible to whoever deployed it. On a map whose
   offline capability is the reason it exists, that failure mode is unacceptable
   as a silent one.

   So: Promise.allSettled over individual cache.put() calls. A missing asset
   degrades one file instead of the whole feature, and what failed is logged and
   reported back to the page.

   THE LIST IS ALSO TIERED
   The basemap is a tile pyramid, so "the detail image" is now a question of how
   many zoom levels are worth carrying offline rather than one large file.
   CRITICAL takes z11, z12 and z13: 155 tiles, 1,596 KB measured, every
   whole-coast view a real viewport can reach, with every zone line readable.
   OPTIONAL adds z10, z14 and z15, another 360 tiles and 3.5 MB. z16 and z17 are
   1,874 tiles and 17 MB and are NOT precached; they arrive on visit and stay
   cached. Somebody who saves the map and walks to the sand has the coast;
   somebody who also zoomed in before leaving signal keeps what they looked at.
   Install waits only for CRITICAL.

   CRITICAL GREW FROM 455 KB TO 1,596 KB ON 2026-09-17 AND IS NOW ON THE 1.6 MB
   LINE, not comfortably under it. Two findings drove it and both are real:

   - z12's box was 22 km tall and a 390 x 844 phone at its landing zoom sees 36 km
     of ground, so the opening view ran out of imagery above and below the coast
     on every portrait phone.
   - z13 needed eight rows where it had five, because flyTo zooms OUT in the
     middle of a flight and the tile layer is updateWhenIdle:false, so a deep link
     requests tiles at a level and a place neither end of the flight visits. One
     deep link 404'd three tiles in row 3878.

   IF THIS HAS TO COME DOWN, move z13 from PRECACHE_CRITICAL to PRECACHE_OPTIONAL
   in tools/build_tiles.py and rerun it. That leaves 75 tiles and about 790 KB
   blocking, and z13 still lands offline seconds later because OPTIONAL starts as
   soon as install resolves. It is a one line change and it is the right lever;
   what must not happen is a level being dropped from both tiers, because a tile
   that is never precached and never on disk is a hole at the water's edge.

   THE TILE LISTS BELOW ARE GENERATED by tools/build_tiles.py, between the
   TILES:BEGIN and TILES:END markers. Do not hand edit them, and do not let them
   drift from web/tiles/: a precache list naming a tile that is not deployed is a
   logged failure on every install, and one naming a tile that IS deployed but is
   missing from the list is a hole in the map at the water's edge.

   HTML IS NETWORK FIRST, EVERYTHING ELSE IS CACHE FIRST
   The document carries the safety verdicts. Somebody with signal must get today's
   copy, not a cached one, so index.html races the network with a short timeout and
   falls back to the cache. The imagery, Leaflet and the geojson are content
   addressed by deploy and change rarely, so they are served from cache and
   revalidated in the background.
   ============================================================================ */

/* BUMP THIS WHENEVER web/tiles/ CHANGES.
   Everything except the HTML is served cache first, so a tile that is already in
   the cache is never re-fetched and a rebuilt pyramid is invisible to anyone who
   has opened the map before. That is not a dev-only annoyance: the black bands
   this version removes stayed on screen through three rebuilds because the old
   part-filled tiles were still being served from cg-map-v1. */
const CACHE = "cg-map-v3";
const STAMP = "cg-map-saved-at";     // written into the cache as a fake response

/* TILES:BEGIN generated by tools/build_tiles.py -- do not edit by hand */
const TILES_CRITICAL = [
  "tiles/11/551/966.jpg",
  "tiles/11/551/967.jpg",
  "tiles/11/551/968.jpg",
  "tiles/11/551/969.jpg",
  "tiles/11/551/970.jpg",
  "tiles/11/551/971.jpg",
  "tiles/11/552/966.jpg",
  "tiles/11/552/967.jpg",
  "tiles/11/552/968.jpg",
  "tiles/11/552/969.jpg",
  "tiles/11/552/970.jpg",
  "tiles/11/552/971.jpg",
  "tiles/11/553/966.jpg",
  "tiles/11/553/967.jpg",
  "tiles/11/553/968.jpg",
  "tiles/11/553/969.jpg",
  "tiles/11/553/970.jpg",
  "tiles/11/553/971.jpg",
  "tiles/11/554/966.jpg",
  "tiles/11/554/967.jpg",
  "tiles/11/554/968.jpg",
  "tiles/11/554/969.jpg",
  "tiles/11/554/970.jpg",
  "tiles/11/554/971.jpg",
  "tiles/11/555/966.jpg",
  "tiles/11/555/967.jpg",
  "tiles/11/555/968.jpg",
  "tiles/11/555/969.jpg",
  "tiles/11/555/970.jpg",
  "tiles/11/555/971.jpg",
  "tiles/12/1104/1934.jpg",
  "tiles/12/1104/1935.jpg",
  "tiles/12/1104/1936.jpg",
  "tiles/12/1104/1937.jpg",
  "tiles/12/1104/1938.jpg",
  "tiles/12/1104/1939.jpg",
  "tiles/12/1104/1940.jpg",
  "tiles/12/1104/1941.jpg",
  "tiles/12/1104/1942.jpg",
  "tiles/12/1105/1934.jpg",
  "tiles/12/1105/1935.jpg",
  "tiles/12/1105/1936.jpg",
  "tiles/12/1105/1937.jpg",
  "tiles/12/1105/1938.jpg",
  "tiles/12/1105/1939.jpg",
  "tiles/12/1105/1940.jpg",
  "tiles/12/1105/1941.jpg",
  "tiles/12/1105/1942.jpg",
  "tiles/12/1106/1934.jpg",
  "tiles/12/1106/1935.jpg",
  "tiles/12/1106/1936.jpg",
  "tiles/12/1106/1937.jpg",
  "tiles/12/1106/1938.jpg",
  "tiles/12/1106/1939.jpg",
  "tiles/12/1106/1940.jpg",
  "tiles/12/1106/1941.jpg",
  "tiles/12/1106/1942.jpg",
  "tiles/12/1107/1934.jpg",
  "tiles/12/1107/1935.jpg",
  "tiles/12/1107/1936.jpg",
  "tiles/12/1107/1937.jpg",
  "tiles/12/1107/1938.jpg",
  "tiles/12/1107/1939.jpg",
  "tiles/12/1107/1940.jpg",
  "tiles/12/1107/1941.jpg",
  "tiles/12/1107/1942.jpg",
  "tiles/12/1108/1934.jpg",
  "tiles/12/1108/1935.jpg",
  "tiles/12/1108/1936.jpg",
  "tiles/12/1108/1937.jpg",
  "tiles/12/1108/1938.jpg",
  "tiles/12/1108/1939.jpg",
  "tiles/12/1108/1940.jpg",
  "tiles/12/1108/1941.jpg",
  "tiles/12/1108/1942.jpg",
  "tiles/13/2210/3871.jpg",
  "tiles/13/2210/3872.jpg",
  "tiles/13/2210/3873.jpg",
  "tiles/13/2210/3874.jpg",
  "tiles/13/2210/3875.jpg",
  "tiles/13/2210/3876.jpg",
  "tiles/13/2210/3877.jpg",
  "tiles/13/2210/3878.jpg",
  "tiles/13/2210/3879.jpg",
  "tiles/13/2210/3880.jpg",
  "tiles/13/2211/3871.jpg",
  "tiles/13/2211/3872.jpg",
  "tiles/13/2211/3873.jpg",
  "tiles/13/2211/3874.jpg",
  "tiles/13/2211/3875.jpg",
  "tiles/13/2211/3876.jpg",
  "tiles/13/2211/3877.jpg",
  "tiles/13/2211/3878.jpg",
  "tiles/13/2211/3879.jpg",
  "tiles/13/2211/3880.jpg",
  "tiles/13/2212/3871.jpg",
  "tiles/13/2212/3872.jpg",
  "tiles/13/2212/3873.jpg",
  "tiles/13/2212/3874.jpg",
  "tiles/13/2212/3875.jpg",
  "tiles/13/2212/3876.jpg",
  "tiles/13/2212/3877.jpg",
  "tiles/13/2212/3878.jpg",
  "tiles/13/2212/3879.jpg",
  "tiles/13/2212/3880.jpg",
  "tiles/13/2213/3871.jpg",
  "tiles/13/2213/3872.jpg",
  "tiles/13/2213/3873.jpg",
  "tiles/13/2213/3874.jpg",
  "tiles/13/2213/3875.jpg",
  "tiles/13/2213/3876.jpg",
  "tiles/13/2213/3877.jpg",
  "tiles/13/2213/3878.jpg",
  "tiles/13/2213/3879.jpg",
  "tiles/13/2213/3880.jpg",
  "tiles/13/2214/3871.jpg",
  "tiles/13/2214/3872.jpg",
  "tiles/13/2214/3873.jpg",
  "tiles/13/2214/3874.jpg",
  "tiles/13/2214/3875.jpg",
  "tiles/13/2214/3876.jpg",
  "tiles/13/2214/3877.jpg",
  "tiles/13/2214/3878.jpg",
  "tiles/13/2214/3879.jpg",
  "tiles/13/2214/3880.jpg",
  "tiles/13/2215/3871.jpg",
  "tiles/13/2215/3872.jpg",
  "tiles/13/2215/3873.jpg",
  "tiles/13/2215/3874.jpg",
  "tiles/13/2215/3875.jpg",
  "tiles/13/2215/3876.jpg",
  "tiles/13/2215/3877.jpg",
  "tiles/13/2215/3878.jpg",
  "tiles/13/2215/3879.jpg",
  "tiles/13/2215/3880.jpg",
  "tiles/13/2216/3871.jpg",
  "tiles/13/2216/3872.jpg",
  "tiles/13/2216/3873.jpg",
  "tiles/13/2216/3874.jpg",
  "tiles/13/2216/3875.jpg",
  "tiles/13/2216/3876.jpg",
  "tiles/13/2216/3877.jpg",
  "tiles/13/2216/3878.jpg",
  "tiles/13/2216/3879.jpg",
  "tiles/13/2216/3880.jpg",
  "tiles/13/2217/3871.jpg",
  "tiles/13/2217/3872.jpg",
  "tiles/13/2217/3873.jpg",
  "tiles/13/2217/3874.jpg",
  "tiles/13/2217/3875.jpg",
  "tiles/13/2217/3876.jpg",
  "tiles/13/2217/3877.jpg",
  "tiles/13/2217/3878.jpg",
  "tiles/13/2217/3879.jpg",
  "tiles/13/2217/3880.jpg"
];
const TILES_OPTIONAL = [
  "tiles/10/275/482.jpg",
  "tiles/10/275/483.jpg",
  "tiles/10/275/484.jpg",
  "tiles/10/275/485.jpg",
  "tiles/10/275/486.jpg",
  "tiles/10/276/482.jpg",
  "tiles/10/276/483.jpg",
  "tiles/10/276/484.jpg",
  "tiles/10/276/485.jpg",
  "tiles/10/276/486.jpg",
  "tiles/10/277/482.jpg",
  "tiles/10/277/483.jpg",
  "tiles/10/277/484.jpg",
  "tiles/10/277/485.jpg",
  "tiles/10/277/486.jpg",
  "tiles/14/4420/7745.jpg",
  "tiles/14/4420/7746.jpg",
  "tiles/14/4420/7747.jpg",
  "tiles/14/4420/7748.jpg",
  "tiles/14/4420/7749.jpg",
  "tiles/14/4420/7750.jpg",
  "tiles/14/4420/7751.jpg",
  "tiles/14/4420/7752.jpg",
  "tiles/14/4420/7753.jpg",
  "tiles/14/4420/7754.jpg",
  "tiles/14/4420/7755.jpg",
  "tiles/14/4420/7756.jpg",
  "tiles/14/4421/7745.jpg",
  "tiles/14/4421/7746.jpg",
  "tiles/14/4421/7747.jpg",
  "tiles/14/4421/7748.jpg",
  "tiles/14/4421/7749.jpg",
  "tiles/14/4421/7750.jpg",
  "tiles/14/4421/7751.jpg",
  "tiles/14/4421/7752.jpg",
  "tiles/14/4421/7753.jpg",
  "tiles/14/4421/7754.jpg",
  "tiles/14/4421/7755.jpg",
  "tiles/14/4421/7756.jpg",
  "tiles/14/4422/7745.jpg",
  "tiles/14/4422/7746.jpg",
  "tiles/14/4422/7747.jpg",
  "tiles/14/4422/7748.jpg",
  "tiles/14/4422/7749.jpg",
  "tiles/14/4422/7750.jpg",
  "tiles/14/4422/7751.jpg",
  "tiles/14/4422/7752.jpg",
  "tiles/14/4422/7753.jpg",
  "tiles/14/4422/7754.jpg",
  "tiles/14/4422/7755.jpg",
  "tiles/14/4422/7756.jpg",
  "tiles/14/4423/7745.jpg",
  "tiles/14/4423/7746.jpg",
  "tiles/14/4423/7747.jpg",
  "tiles/14/4423/7748.jpg",
  "tiles/14/4423/7749.jpg",
  "tiles/14/4423/7750.jpg",
  "tiles/14/4423/7751.jpg",
  "tiles/14/4423/7752.jpg",
  "tiles/14/4423/7753.jpg",
  "tiles/14/4423/7754.jpg",
  "tiles/14/4423/7755.jpg",
  "tiles/14/4423/7756.jpg",
  "tiles/14/4424/7745.jpg",
  "tiles/14/4424/7746.jpg",
  "tiles/14/4424/7747.jpg",
  "tiles/14/4424/7748.jpg",
  "tiles/14/4424/7749.jpg",
  "tiles/14/4424/7750.jpg",
  "tiles/14/4424/7751.jpg",
  "tiles/14/4424/7752.jpg",
  "tiles/14/4424/7753.jpg",
  "tiles/14/4424/7754.jpg",
  "tiles/14/4424/7755.jpg",
  "tiles/14/4424/7756.jpg",
  "tiles/14/4425/7745.jpg",
  "tiles/14/4425/7746.jpg",
  "tiles/14/4425/7747.jpg",
  "tiles/14/4425/7748.jpg",
  "tiles/14/4425/7749.jpg",
  "tiles/14/4425/7750.jpg",
  "tiles/14/4425/7751.jpg",
  "tiles/14/4425/7752.jpg",
  "tiles/14/4425/7753.jpg",
  "tiles/14/4425/7754.jpg",
  "tiles/14/4425/7755.jpg",
  "tiles/14/4425/7756.jpg",
  "tiles/14/4426/7745.jpg",
  "tiles/14/4426/7746.jpg",
  "tiles/14/4426/7747.jpg",
  "tiles/14/4426/7748.jpg",
  "tiles/14/4426/7749.jpg",
  "tiles/14/4426/7750.jpg",
  "tiles/14/4426/7751.jpg",
  "tiles/14/4426/7752.jpg",
  "tiles/14/4426/7753.jpg",
  "tiles/14/4426/7754.jpg",
  "tiles/14/4426/7755.jpg",
  "tiles/14/4426/7756.jpg",
  "tiles/14/4427/7745.jpg",
  "tiles/14/4427/7746.jpg",
  "tiles/14/4427/7747.jpg",
  "tiles/14/4427/7748.jpg",
  "tiles/14/4427/7749.jpg",
  "tiles/14/4427/7750.jpg",
  "tiles/14/4427/7751.jpg",
  "tiles/14/4427/7752.jpg",
  "tiles/14/4427/7753.jpg",
  "tiles/14/4427/7754.jpg",
  "tiles/14/4427/7755.jpg",
  "tiles/14/4427/7756.jpg",
  "tiles/14/4428/7745.jpg",
  "tiles/14/4428/7746.jpg",
  "tiles/14/4428/7747.jpg",
  "tiles/14/4428/7748.jpg",
  "tiles/14/4428/7749.jpg",
  "tiles/14/4428/7750.jpg",
  "tiles/14/4428/7751.jpg",
  "tiles/14/4428/7752.jpg",
  "tiles/14/4428/7753.jpg",
  "tiles/14/4428/7754.jpg",
  "tiles/14/4428/7755.jpg",
  "tiles/14/4428/7756.jpg",
  "tiles/14/4429/7745.jpg",
  "tiles/14/4429/7746.jpg",
  "tiles/14/4429/7747.jpg",
  "tiles/14/4429/7748.jpg",
  "tiles/14/4429/7749.jpg",
  "tiles/14/4429/7750.jpg",
  "tiles/14/4429/7751.jpg",
  "tiles/14/4429/7752.jpg",
  "tiles/14/4429/7753.jpg",
  "tiles/14/4429/7754.jpg",
  "tiles/14/4429/7755.jpg",
  "tiles/14/4429/7756.jpg",
  "tiles/14/4430/7745.jpg",
  "tiles/14/4430/7746.jpg",
  "tiles/14/4430/7747.jpg",
  "tiles/14/4430/7748.jpg",
  "tiles/14/4430/7749.jpg",
  "tiles/14/4430/7750.jpg",
  "tiles/14/4430/7751.jpg",
  "tiles/14/4430/7752.jpg",
  "tiles/14/4430/7753.jpg",
  "tiles/14/4430/7754.jpg",
  "tiles/14/4430/7755.jpg",
  "tiles/14/4430/7756.jpg",
  "tiles/14/4431/7745.jpg",
  "tiles/14/4431/7746.jpg",
  "tiles/14/4431/7747.jpg",
  "tiles/14/4431/7748.jpg",
  "tiles/14/4431/7749.jpg",
  "tiles/14/4431/7750.jpg",
  "tiles/14/4431/7751.jpg",
  "tiles/14/4431/7752.jpg",
  "tiles/14/4431/7753.jpg",
  "tiles/14/4431/7754.jpg",
  "tiles/14/4431/7755.jpg",
  "tiles/14/4431/7756.jpg",
  "tiles/14/4432/7745.jpg",
  "tiles/14/4432/7746.jpg",
  "tiles/14/4432/7747.jpg",
  "tiles/14/4432/7748.jpg",
  "tiles/14/4432/7749.jpg",
  "tiles/14/4432/7750.jpg",
  "tiles/14/4432/7751.jpg",
  "tiles/14/4432/7752.jpg",
  "tiles/14/4432/7753.jpg",
  "tiles/14/4432/7754.jpg",
  "tiles/14/4432/7755.jpg",
  "tiles/14/4432/7756.jpg",
  "tiles/14/4433/7745.jpg",
  "tiles/14/4433/7746.jpg",
  "tiles/14/4433/7747.jpg",
  "tiles/14/4433/7748.jpg",
  "tiles/14/4433/7749.jpg",
  "tiles/14/4433/7750.jpg",
  "tiles/14/4433/7751.jpg",
  "tiles/14/4433/7752.jpg",
  "tiles/14/4433/7753.jpg",
  "tiles/14/4433/7754.jpg",
  "tiles/14/4433/7755.jpg",
  "tiles/14/4433/7756.jpg",
  "tiles/14/4434/7745.jpg",
  "tiles/14/4434/7746.jpg",
  "tiles/14/4434/7747.jpg",
  "tiles/14/4434/7748.jpg",
  "tiles/14/4434/7749.jpg",
  "tiles/14/4434/7750.jpg",
  "tiles/14/4434/7751.jpg",
  "tiles/14/4434/7752.jpg",
  "tiles/14/4434/7753.jpg",
  "tiles/14/4434/7754.jpg",
  "tiles/14/4434/7755.jpg",
  "tiles/14/4434/7756.jpg",
  "tiles/15/8847/15496.jpg",
  "tiles/15/8847/15497.jpg",
  "tiles/15/8847/15498.jpg",
  "tiles/15/8847/15499.jpg",
  "tiles/15/8847/15500.jpg",
  "tiles/15/8847/15501.jpg",
  "tiles/15/8847/15502.jpg",
  "tiles/15/8847/15503.jpg",
  "tiles/15/8847/15504.jpg",
  "tiles/15/8847/15505.jpg",
  "tiles/15/8847/15506.jpg",
  "tiles/15/8848/15496.jpg",
  "tiles/15/8848/15497.jpg",
  "tiles/15/8848/15498.jpg",
  "tiles/15/8848/15499.jpg",
  "tiles/15/8848/15500.jpg",
  "tiles/15/8848/15501.jpg",
  "tiles/15/8848/15502.jpg",
  "tiles/15/8848/15503.jpg",
  "tiles/15/8848/15504.jpg",
  "tiles/15/8848/15505.jpg",
  "tiles/15/8848/15506.jpg",
  "tiles/15/8849/15496.jpg",
  "tiles/15/8849/15497.jpg",
  "tiles/15/8849/15498.jpg",
  "tiles/15/8849/15499.jpg",
  "tiles/15/8849/15500.jpg",
  "tiles/15/8849/15501.jpg",
  "tiles/15/8849/15502.jpg",
  "tiles/15/8849/15503.jpg",
  "tiles/15/8849/15504.jpg",
  "tiles/15/8849/15505.jpg",
  "tiles/15/8849/15506.jpg",
  "tiles/15/8850/15496.jpg",
  "tiles/15/8850/15497.jpg",
  "tiles/15/8850/15498.jpg",
  "tiles/15/8850/15499.jpg",
  "tiles/15/8850/15500.jpg",
  "tiles/15/8850/15501.jpg",
  "tiles/15/8850/15502.jpg",
  "tiles/15/8850/15503.jpg",
  "tiles/15/8850/15504.jpg",
  "tiles/15/8850/15505.jpg",
  "tiles/15/8850/15506.jpg",
  "tiles/15/8851/15496.jpg",
  "tiles/15/8851/15497.jpg",
  "tiles/15/8851/15498.jpg",
  "tiles/15/8851/15499.jpg",
  "tiles/15/8851/15500.jpg",
  "tiles/15/8851/15501.jpg",
  "tiles/15/8851/15502.jpg",
  "tiles/15/8851/15503.jpg",
  "tiles/15/8851/15504.jpg",
  "tiles/15/8851/15505.jpg",
  "tiles/15/8851/15506.jpg",
  "tiles/15/8852/15496.jpg",
  "tiles/15/8852/15497.jpg",
  "tiles/15/8852/15498.jpg",
  "tiles/15/8852/15499.jpg",
  "tiles/15/8852/15500.jpg",
  "tiles/15/8852/15501.jpg",
  "tiles/15/8852/15502.jpg",
  "tiles/15/8852/15503.jpg",
  "tiles/15/8852/15504.jpg",
  "tiles/15/8852/15505.jpg",
  "tiles/15/8852/15506.jpg",
  "tiles/15/8853/15496.jpg",
  "tiles/15/8853/15497.jpg",
  "tiles/15/8853/15498.jpg",
  "tiles/15/8853/15499.jpg",
  "tiles/15/8853/15500.jpg",
  "tiles/15/8853/15501.jpg",
  "tiles/15/8853/15502.jpg",
  "tiles/15/8853/15503.jpg",
  "tiles/15/8853/15504.jpg",
  "tiles/15/8853/15505.jpg",
  "tiles/15/8853/15506.jpg",
  "tiles/15/8854/15496.jpg",
  "tiles/15/8854/15497.jpg",
  "tiles/15/8854/15498.jpg",
  "tiles/15/8854/15499.jpg",
  "tiles/15/8854/15500.jpg",
  "tiles/15/8854/15501.jpg",
  "tiles/15/8854/15502.jpg",
  "tiles/15/8854/15503.jpg",
  "tiles/15/8854/15504.jpg",
  "tiles/15/8854/15505.jpg",
  "tiles/15/8854/15506.jpg",
  "tiles/15/8855/15496.jpg",
  "tiles/15/8855/15497.jpg",
  "tiles/15/8855/15498.jpg",
  "tiles/15/8855/15499.jpg",
  "tiles/15/8855/15500.jpg",
  "tiles/15/8855/15501.jpg",
  "tiles/15/8855/15502.jpg",
  "tiles/15/8855/15503.jpg",
  "tiles/15/8855/15504.jpg",
  "tiles/15/8855/15505.jpg",
  "tiles/15/8855/15506.jpg",
  "tiles/15/8856/15496.jpg",
  "tiles/15/8856/15497.jpg",
  "tiles/15/8856/15498.jpg",
  "tiles/15/8856/15499.jpg",
  "tiles/15/8856/15500.jpg",
  "tiles/15/8856/15501.jpg",
  "tiles/15/8856/15502.jpg",
  "tiles/15/8856/15503.jpg",
  "tiles/15/8856/15504.jpg",
  "tiles/15/8856/15505.jpg",
  "tiles/15/8856/15506.jpg",
  "tiles/15/8857/15496.jpg",
  "tiles/15/8857/15497.jpg",
  "tiles/15/8857/15498.jpg",
  "tiles/15/8857/15499.jpg",
  "tiles/15/8857/15500.jpg",
  "tiles/15/8857/15501.jpg",
  "tiles/15/8857/15502.jpg",
  "tiles/15/8857/15503.jpg",
  "tiles/15/8857/15504.jpg",
  "tiles/15/8857/15505.jpg",
  "tiles/15/8857/15506.jpg",
  "tiles/15/8858/15496.jpg",
  "tiles/15/8858/15497.jpg",
  "tiles/15/8858/15498.jpg",
  "tiles/15/8858/15499.jpg",
  "tiles/15/8858/15500.jpg",
  "tiles/15/8858/15501.jpg",
  "tiles/15/8858/15502.jpg",
  "tiles/15/8858/15503.jpg",
  "tiles/15/8858/15504.jpg",
  "tiles/15/8858/15505.jpg",
  "tiles/15/8858/15506.jpg",
  "tiles/15/8859/15496.jpg",
  "tiles/15/8859/15497.jpg",
  "tiles/15/8859/15498.jpg",
  "tiles/15/8859/15499.jpg",
  "tiles/15/8859/15500.jpg",
  "tiles/15/8859/15501.jpg",
  "tiles/15/8859/15502.jpg",
  "tiles/15/8859/15503.jpg",
  "tiles/15/8859/15504.jpg",
  "tiles/15/8859/15505.jpg",
  "tiles/15/8859/15506.jpg",
  "tiles/15/8860/15496.jpg",
  "tiles/15/8860/15497.jpg",
  "tiles/15/8860/15498.jpg",
  "tiles/15/8860/15499.jpg",
  "tiles/15/8860/15500.jpg",
  "tiles/15/8860/15501.jpg",
  "tiles/15/8860/15502.jpg",
  "tiles/15/8860/15503.jpg",
  "tiles/15/8860/15504.jpg",
  "tiles/15/8860/15505.jpg",
  "tiles/15/8860/15506.jpg",
  "tiles/15/8861/15496.jpg",
  "tiles/15/8861/15497.jpg",
  "tiles/15/8861/15498.jpg",
  "tiles/15/8861/15499.jpg",
  "tiles/15/8861/15500.jpg",
  "tiles/15/8861/15501.jpg",
  "tiles/15/8861/15502.jpg",
  "tiles/15/8861/15503.jpg",
  "tiles/15/8861/15504.jpg",
  "tiles/15/8861/15505.jpg",
  "tiles/15/8861/15506.jpg"
];
/* TILES:END */

/* Relative, not absolute. The map is served from / in production and from
   /mapa/app/ inside the local site build, and a leading slash would break one of
   the two. The worker's scope already anchors these. */
const CRITICAL = [
  "./",
  "index.html",
  "manifest.json",
  "vendor/leaflet.js",
  "vendor/leaflet.css",
  "data/cg-hazards.geojson",

  /* The map's own linework, and it is CRITICAL rather than optional because
     without either of these the page draws a basemap with nothing on it. There
     is no fallback copy of the geometry in the HTML any more: the nine-point
     `line:` arrays were the broken ones, and keeping a broken copy as a standby
     is worse than failing to draw, because a hazard line in the wrong place is a
     claim rather than a gap. See docs/handoffs/2026-09-14. */
  "geometry.js",
  "data/zones-geometry.json",

  /* Atkinson Hyperlegible, self hosted, Regular and Bold only.

     A FONT IS A SAFETY ASSET ON THIS MAP. The instruction is the largest and the
     most consequential text on every card, and it is set in a face chosen
     because its letterforms are unambiguous to a low-vision reader in sunlight.
     Falling back to the system stack offline would silently return the map to
     the typography the accessibility pass rejected, at the exact moment the
     reader has no signal to fix it.

     NAMED, NOT GLOBBED: a service worker cannot list a directory. These two
     filenames are a contract with web/fonts/. If the files are not there, the
     precache logs two failures and degrades to the system stack rather than
     killing the install, which is what the allSettled loop below is for. */
  "fonts/AtkinsonHyperlegible-Regular.woff2",
  "fonts/AtkinsonHyperlegible-Bold.woff2"
].concat(TILES_CRITICAL);
/* Every icon manifest.json names, plus the Apple touch icon, which it does not.

   icon-maskable-512.png was in the manifest and not here. That is the quiet
   failure mode for an installed PWA: the icon is only fetched when the launcher
   draws it, which on Android is after the install prompt is accepted and may be
   the first moment the device is offline. The app would install and then show a
   default glyph, and nothing would report it.

   tools/build_tiles.py now cross checks this list against web/icons/ and
   manifest.json on every run, so the next one cannot drift silently. */
const OPTIONAL = [
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png"
].concat(TILES_OPTIONAL);

/* One asset, fetched fresh from the network and written on its own, so a failure
   is one missing file rather than a dead feature. cache:"reload" bypasses the
   HTTP cache: a precache built from stale bytes is a stale safety map that
   believes it is current. */
async function put(cache, url){
  const res = await fetch(new Request(url, {cache:"reload"}));
  if(!res.ok) throw new Error(url + " -> " + res.status);
  await cache.put(url, res);
  return url;
}

async function precache(urls){
  const cache = await caches.open(CACHE);
  const results = await Promise.allSettled(urls.map(u => put(cache, u)));
  const failed = results
    .map((r, i) => r.status === "rejected" ? urls[i] : null)
    .filter(Boolean);
  if(failed.length) console.warn("[cg-sw] not cached:", failed);
  return {ok: urls.length - failed.length, failed};
}

/* The timestamp is only written when the WHOLE critical set landed.
   Stamping after a partial precache would put a fresh date on a cache that is
   missing pieces, and the date is the one thing the interface uses to tell
   somebody how old the advice in front of them is. Better for the bar to read
   "not saved" while most of it is there than for it to read "saved just now"
   while the geojson is missing. */
async function stamp(){
  const cache = await caches.open(CACHE);
  await cache.put(STAMP, new Response(String(Date.now())));
}
async function broadcast(msg){
  const clients = await self.clients.matchAll();
  clients.forEach(c => c.postMessage(msg));
}
async function readStamp(){
  const cache = await caches.open(CACHE);
  const r = await cache.match(STAMP);
  return r ? Number(await r.text()) : null;
}

self.addEventListener("install", e=>{
  e.waitUntil((async ()=>{
    const res = await precache(CRITICAL);
    if(res.failed.length === 0) await stamp();
    else console.error("[cg-sw] incomplete precache, not stamping:", res.failed);
    // the detail image is allowed to arrive late and is allowed to fail
    precache(OPTIONAL).catch(()=>{});
  })());
});

self.addEventListener("activate", e=>{
  e.waitUntil((async ()=>{
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
    await broadcast({savedAt: await readStamp()});
  })());
});

const isDoc = req => req.mode === "navigate" ||
                     (req.headers.get("accept") || "").includes("text/html");

/* Race the network, but not forever. On a beach the connection is not down, it is
   slow, and a fetch that hangs for thirty seconds is worse than a cached copy
   served instantly with its date on it. */
function timed(promise, ms){
  return new Promise((resolve, reject)=>{
    const t = setTimeout(()=>reject(new Error("timeout")), ms);
    promise.then(v=>{ clearTimeout(t); resolve(v); },
                 e=>{ clearTimeout(t); reject(e); });
  });
}

self.addEventListener("fetch", e=>{
  const req = e.request;
  if(req.method !== "GET") return;
  const url = new URL(req.url);
  if(url.origin !== location.origin) return;   // tel: and Google Maps links, untouched

  if(isDoc(req)){
    // network first: the document carries the verdicts
    e.respondWith((async ()=>{
      try{
        const res = await timed(fetch(req), 4000);
        const cache = await caches.open(CACHE);
        cache.put("index.html", res.clone());
        stamp();
        return res;
      }catch(err){
        const hit = await caches.match("index.html") || await caches.match("./");
        return hit || Response.error();
      }
    })());
    return;
  }

  // everything else: cache first, revalidate quietly behind it
  e.respondWith((async ()=>{
    const hit = await caches.match(req, {ignoreSearch:false});
    const net = fetch(req).then(res=>{
      if(res.ok) caches.open(CACHE).then(c => c.put(req, res.clone()));
      return res;
    }).catch(()=>null);
    return hit || (await net) || Response.error();
  })());
});

self.addEventListener("message", e=>{
  const d = e.data || {};

  if(d.action === "SKIP_WAITING"){
    self.skipWaiting();
    return;
  }

  if(d.action === "SAVED_AT"){
    readStamp().then(at=>{
      if(e.source) e.source.postMessage({savedAt: at});
    });
    return;
  }

  /* Manual refresh from the saved-copy bar. Re-fetches everything from the
     network and answers on the port the page opened, so the bar can say whether
     it worked instead of silently pretending it did.

     A failed refresh must leave BOTH the cache and the displayed date exactly as
     they were. The first version of this stamped unconditionally and then
     broadcast the new date to every client, so tapping refresh with no signal
     moved the timestamp forward without a single byte having been fetched. That
     is the interface claiming more currency than the data has, which is the one
     rule this whole file exists to keep. */
  if(d.action === "REFRESH"){
    const port = e.ports && e.ports[0];
    (async ()=>{
      const res = await precache(CRITICAL);
      const ok = res.failed.length === 0;
      if(ok){
        await stamp();
        precache(OPTIONAL).catch(()=>{});
      }
      const at = await readStamp();
      if(port) port.postMessage({ok, failed: res.failed, savedAt: at});
      if(ok) await broadcast({savedAt: at});
    })().catch(err=>{
      if(port) port.postMessage({ok:false, error:String(err)});
    });
  }
});
